// js/menu-data.js

const databaseMenu = [
    { id: 101, nama: "Kornet", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 102, nama: "Pentol", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 103, nama: "Sosis Kecil", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 104, nama: "Sosis Merah", hargaBeli: 0, harga: 1500, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 105, nama: "Sosis Salju", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 106, nama: "Sosis Jumbo", hargaBeli: 0, harga: 5000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 107, nama: "Bintang", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 108, nama: "Tempura", hargaBeli: 0, harga: 1500, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 109, nama: "Scallop", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 110, nama: "Bakso Ikan", hargaBeli: 0, harga: 1500, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 111, nama: "Tahu Bakso", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 112, nama: "Dumpling Ayam", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 113, nama: "Dumpling Keju", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 114, nama: "Dumpling Spicy", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 115, nama: "Odeng", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 116, nama: "Cikua", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 117, nama: "Fish Roll", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 118, nama: "Crab Stik", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 119, nama: "Ekor Udang", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 120, nama: "Udang Gulung", hargaBeli: 0, harga: 2500, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 121, nama: "Kembang Cumi", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 122, nama: "Pilus", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 123, nama: "Cuanki Lidah", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 124, nama: "Siomay Kering", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 125, nama: "Krupuk Rafael", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 126, nama: "Krupuk Orange", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 127, nama: "Krupuk Warna", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 128, nama: "Krupuk Bintang", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 129, nama: "Krupuk Tangga", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 130, nama: "Jamur Enoki", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 131, nama: "Mie lombok", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 132, nama: "Makaroni", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 133, nama: "Tofu", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 134, nama: "Sosis Kamil", hargaBeli: 0, harga: 1500, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 135, nama: "Bentuk Udang", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "topping" },
    { id: 136, nama: "Krupuk Pedo", hargaBeli: 0, harga: 1000, isi: 1, satuan: "pcs", kategori: "topping" },

    { id: 201, nama: "Mie Tulang", hargaBeli: 0, harga: 8000, isi: 1, satuan: "porsi", kategori: "makanan" },
    { id: 202, nama: "Gado gado", hargaBeli: 0, harga: 12000, isi: 1, satuan: "porsi", kategori: "makanan" },
    { id: 203, nama: "Seblak All Varian", hargaBeli: 0, harga: 8000, isi: 1, satuan: "porsi", kategori: "makanan" },
    { id: 204, nama: "Nasi Kucing", hargaBeli: 0, harga: 5000, isi: 1, satuan: "bungkus", kategori: "makanan" },
    { id: 205, nama: "Nasi Bakar", hargaBeli: 0, harga: 5000, isi: 1, satuan: "bungkus", kategori: "makanan" },
    { id: 206, nama: "Sayap bakar", hargaBeli: 0, harga: 5000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 207, nama: "Kepala (Mulai)", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 208, nama: "Ceker (Mulai)", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 209, nama: "Tempe bacem", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 210, nama: "Tahu bacem", hargaBeli: 0, harga: 2000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 211, nama: "Telur puyuh bakar", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 212, nama: "Sate Usus", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 213, nama: "Sate Rempelo Ati", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 214, nama: "Sate Lok Lok", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 215, nama: "Sosis bakar", hargaBeli: 0, harga: 8000, isi: 1, satuan: "pcs", kategori: "makanan" },
    { id: 216, nama: "Paket nasi babat + Esteh", hargaBeli: 0, harga: 20000, isi: 1, satuan: "porsi", kategori: "makanan" },
    { id: 217, nama: "Siomay + telur", hargaBeli: 0, harga: 10000, isi: 1, satuan: "porsi", kategori: "makanan" },

    { id: 301, nama: "Es Teh", hargaBeli: 0, harga: 4000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 302, nama: "Es Dawet", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 303, nama: "Es Teller", hargaBeli: 0, harga: 10000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 304, nama: "Pop Ice", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 305, nama: "Nutri sari Ice", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 306, nama: "Milo ice", hargaBeli: 0, harga: 6000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 307, nama: "Good Day ice", hargaBeli: 0, harga: 6000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 308, nama: "Bonteh Matcha", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 309, nama: "Bonteh Tarik", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 310, nama: "Uyu Ice", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 311, nama: "Beng Beng Ice", hargaBeli: 0, harga: 6000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 312, nama: "Chocolatos Ice", hargaBeli: 0, harga: 6000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 313, nama: "Kuku Bima Susu Ice", hargaBeli: 0, harga: 7000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 314, nama: "Extra Jos Susu Ice", hargaBeli: 0, harga: 7000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 315, nama: "Hemaviton Susu Ice", hargaBeli: 0, harga: 7000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 316, nama: "Milk Ice", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },
    { id: 317, nama: "Top Coffee Gula aren Ice", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "dingin" },

    { id: 401, nama: "Teh Hangat", hargaBeli: 0, harga: 4000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 402, nama: "Kopi Hitam Racik", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 403, nama: "Top Coffee Gula aren panas", hargaBeli: 0, harga: 6000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 404, nama: "Susu Jahe Panas", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 405, nama: "Top Kopi Susu", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 406, nama: "Kopi Susu Racik", hargaBeli: 0, harga: 6000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 407, nama: "Kopi Kapal Api", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 408, nama: "Top Kopi HItam", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 409, nama: "Kopi Brontoseno", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 410, nama: "Kopi Luwak Hitam", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },
    { id: 411, nama: "Luwak White Coffee", hargaBeli: 0, harga: 5000, isi: 1, satuan: "cup", kategori: "panas" },

    { id: 501, nama: "Roti Nolanda", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "jajanan" },
    { id: 502, nama: "Roti Sisir Bareto", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "jajanan" },
    { id: 503, nama: "Batagor Ikan (1 porsi)", hargaBeli: 0, harga: 5000, isi: 1, satuan: "porsi", kategori: "jajanan" },
    { id: 504, nama: "Cimol", hargaBeli: 0, harga: 3000, isi: 1, satuan: "porsi", kategori: "jajanan" },
    { id: 505, nama: "Surya (1 batang)", hargaBeli: 0, harga: 3000, isi: 1, satuan: "pcs", kategori: "jajanan" }
];