// js/menu-data.js

const databaseMenu = [
    { id: 101, nama: "Kornet", harga: 1000, kategori: "topping" },
    { id: 102, nama: "Pentol", harga: 1000, kategori: "topping" },
    { id: 103, nama: "Sosis Kecil", harga: 1000, kategori: "topping" },
    { id: 104, nama: "Sosis Merah", harga: 1500, kategori: "topping" },
    { id: 105, nama: "Sosis Salju", harga: 2000, kategori: "topping" },
    { id: 106, nama: "Sosis Jumbo", harga: 5000, kategori: "topping" },
    { id: 107, nama: "Bintang", harga: 1000, kategori: "topping" },
    { id: 108, nama: "Tempura", harga: 1500, kategori: "topping" },
    { id: 109, nama: "Scallop", harga: 1000, kategori: "topping" },
    { id: 110, nama: "Bakso Ikan", harga: 1500, kategori: "topping" },
    { id: 111, nama: "Tahu Bakso", harga: 1000, kategori: "topping" },
    { id: 112, nama: "Dumpling Ayam", harga: 2000, kategori: "topping" },
    { id: 113, nama: "Dumpling Keju", harga: 2000, kategori: "topping" },
    { id: 114, nama: "Dumpling Spicy", harga: 2000, kategori: "topping" },
    { id: 115, nama: "Odeng", harga: 2000, kategori: "topping" },
    { id: 116, nama: "Cikua", harga: 1000, kategori: "topping" },
    { id: 117, nama: "Fish Roll", harga: 2000, kategori: "topping" },
    { id: 118, nama: "Crab Stik", harga: 2000, kategori: "topping" },
    { id: 119, nama: "Ekor Udang", harga: 2000, kategori: "topping" },
    { id: 120, nama: "Udang Gulung", harga: 2500, kategori: "topping" },
    { id: 121, nama: "Kembang Cumi", harga: 1000, kategori: "topping" },
    { id: 122, nama: "Pilus", harga: 1000, kategori: "topping" },
    { id: 123, nama: "Cuanki Lidah", harga: 2000, kategori: "topping" },
    { id: 124, nama: "Siomay Kering", harga: 2000, kategori: "topping" },
    { id: 125, nama: "Krupuk Rafael", harga: 1000, kategori: "topping" },
    { id: 126, nama: "Krupuk Orange", harga: 1000, kategori: "topping" },
    { id: 127, nama: "Krupuk Warna", harga: 1000, kategori: "topping" },
    { id: 128, nama: "Krupuk Bintang", harga: 1000, kategori: "topping" },
    { id: 129, nama: "Krupuk Tangga", harga: 1000, kategori: "topping" },
    { id: 130, nama: "Jamur Enoki", harga: 1000, kategori: "topping" },
    { id: 131, nama: "Mie lombok", harga: 1000, kategori: "topping" },
    { id: 132, nama: "Makaroni", harga: 1000, kategori: "topping" },
    { id: 133, nama: "Tofu", harga: 2000, kategori: "topping" },
    { id: 134, nama: "Sosis Kamil", harga: 1500, kategori: "topping" },
    { id: 135, nama: "Bentuk Udang", harga: 2000, kategori: "topping" },
    { id: 136, nama: "Krupuk Pedo", harga: 1000, kategori: "topping" },

    { id: 201, nama: "Mie Tulang", harga: 8000, kategori: "makanan" },
    { id: 202, nama: "Gado gado", harga: 12000, kategori: "makanan" },
    { id: 203, nama: "Seblak All Varian", harga: 8000, kategori: "makanan" },
    { id: 204, nama: "Nasi Kucing", harga: 5000, kategori: "makanan" },
    { id: 205, nama: "Nasi Bakar", harga: 5000, kategori: "makanan" },
    { id: 206, nama: "Sayap bakar", harga: 5000, kategori: "makanan" },
    { id: 207, nama: "Kepala (Mulai)", harga: 3000, kategori: "makanan" },
    { id: 208, nama: "Ceker (Mulai)", harga: 2000, kategori: "makanan" },
    { id: 209, nama: "Tempe bacem", harga: 2000, kategori: "makanan" },
    { id: 210, nama: "Tahu bacem", harga: 2000, kategori: "makanan" },
    { id: 211, font: "bold", nama: "Telur puyuh bakar", harga: 3000, kategori: "makanan" },
    { id: 212, nama: "Sate Usus", harga: 3000, kategori: "makanan" },
    { id: 213, nama: "Sate Rempelo Ati", harga: 3000, kategori: "makanan" },
    { id: 214, nama: "Sate Lok Lok", harga: 3000, kategori: "makanan" },
    { id: 215, nama: "Sosis bakar", harga: 8000, kategori: "makanan" },
    { id: 216, nama: "Paket nasi babat + Esteh", harga: 20000, kategori: "makanan" },
    { id: 217, nama: "Siomay + telur", harga: 10000, kategori: "makanan" },

    { id: 301, nama: "Es Teh", harga: 4000, kategori: "dingin" },
    { id: 302, nama: "Es Dawet", font: "light", harga: 5000, kategori: "dingin" },
    { id: 303, nama: "Es Teller", harga: 10000, kategori: "dingin" },
    { id: 304, font: "light", nama: "Pop Ice", harga: 5000, kategori: "dingin" },
    { id: 305, nama: "Nutri sari Ice", font: "light", harga: 5000, kategori: "dingin" },
    { id: 306, nama: "Milo ice", harga: 6000, kategori: "dingin" },
    { id: 307, nama: "Good Day ice", harga: 6000, kategori: "dingin" },
    { id: 308, nama: "Bonteh Matcha", harga: 5000, kategori: "dingin" },
    { id: 309, nama: "Bonteh Tarik", harga: 5000, kategori: "dingin" },
    { id: 310, nama: "Uyu Ice", font: "light", harga: 5000, kategori: "dingin" },
    { id: 311, nama: "Beng Beng Ice", harga: 6000, kategori: "dingin" },
    { id: 312, nama: "Chocolatos Ice", harga: 6000, kategori: "dingin" },
    { id: 313, nama: "Kuku Bima Susu Ice", harga: 7000, kategori: "dingin" },
    { id: 314, nama: "Extra Jos Susu Ice", harga: 7000, kategori: "dingin" },
    { id: 315, nama: "Hemaviton Susu Ice", harga: 7000, kategori: "dingin" },
    { id: 316, nama: "Milk Ice", harga: 5000, kategori: "dingin" },
    { id: 317, nama: "Top Coffee Gula aren Ice", harga: 5000, kategori: "dingin" },

    { id: 401, nama: "Teh Hangat", harga: 4000, kategori: "panas" },
    { id: 402, nama: "Kopi Hitam Racik", harga: 5000, kategori: "panas" },
    { id: 403, nama: "Top Coffee Gula aren panas", harga: 6000, kategori: "panas" },
    { id: 404, nama: "Susu Jahe Panas", harga: 5000, kategori: "panas" },
    { id: 405, nama: "Top Kopi Susu", harga: 5000, kategori: "panas" },
    { id: 406, nama: "Kopi Susu Racik", harga: 6000, kategori: "panas" },
    { id: 407, nama: "Kopi Kapal Api", harga: 5000, kategori: "panas" },
    { id: 408, nama: "Top Kopi HItam", harga: 5000, kategori: "panas" },
    { id: 409, nama: "Kopi Brontoseno", harga: 5000, kategori: "panas" },
    { id: 410, nama: "Kopi Luwak Hitam", harga: 5000, kategori: "panas" },
    { id: 411, nama: "Luwak White Coffee", harga: 5000, kategori: "panas" },

    { id: 501, nama: "Roti Nolanda", harga: 3000, kategori: "jajanan" },
    { id: 502, nama: "Roti Sisir Bareto", harga: 3000, kategori: "jajanan" },
    { id: 503, nama: "Batagor Ikan (1 porsi)", harga: 5000, kategori: "jajanan" },
    { id: 504, nama: "Cimol", harga: 3000, kategori: "jajanan" },
    { id: 505, nama: "Surya (1 batang)", harga: 3000, kategori: "jajanan" }
];